#!/bin/bash
EDITOR="vi" bin/rails credentials:edit
~                                                                                                                                                                   
~                                                                                                                                                                   
~     
